name: Issue Course Certificate

# Workflow can be triggered through the API
trigger:
  type: api

input:
  type: 'object'
  properties:
    studentNumber:
      type: string
      description: The student number
    studentName:
      type: string
      description: The name of the student
    courseId:
      type: string
      description: The id of the course
    courseName:
      type: string
      description: The id of the course
  required:
    - studentNumber
    - studentName
    - courseId
    - courseName

actions:
  # Setup the connection by showing the QR code in your client
  - id: createConnection
    name: didcomm/createConnection@v1
    attributes:
      label: Silicon University

  # Issue the course credential
  - id: issueCredential
    name: didcomm/issueCredential@v1
    attributes:
      connectionId: $.actions.createConnection.output.connection.connectionId
      anoncreds:
        # Make sure the credential template is created with the same attributes (studentName, studentNumber, courseId, courseName) as used below.
        credentialDefinitionId: did:cheqd:testnet:0d0a615e-5295-4137-8fda-0d95aca5d32b/resources/2ce68d1b-b79c-4d5e-ba7f-d321688bde8f
        attributes:
          courseId: $.input.courseId
          courseName: $.input.courseName
          studentNumber: $.input.studentNumber
          studentName: $.input.studentName
