name: Issue course certificate

trigger:
  type: api

input:
  type: 'object'
  properties:
    studentNumber:
      type: string
      description: The student number
    studentName:
      type: string
      description: The name of the student
    courseId:
      type: string
      description: The id of the course
    courseName:
      type: string
      description: The name of the course
  required:
    - studentNumber
    - studentName
    - courseId
    - courseName

actions:
  # Setup the connection by showing the invitationUrl as a QR code in your client
  - id: createConnection
    name: didcomm/createConnection@v1
    attributes:
      label: Silicon University

  # Issue the course credential with the connection
  - id: issueCredential
    name: didcomm/issueCredential@v1
    attributes:
      connectionId: $.actions.createConnection.output.connection.connectionId
      anoncreds:
        # Make sure the credential template is created with the same attributes (studentName, studentNumber, courseId, courseName) as used below.
        credentialDefinitionId: <YOUR_CREDENTIAL_DEFINITION_ID>
        attributes:
          courseId: $.input.courseId
          courseName: $.input.courseName
          studentNumber: $.input.studentNumber
          studentName: $.input.studentName
