name: Register Course Credential

trigger:
  type: api

actions:
  - id: createSchema
    name: anoncreds/createSchema@v1
    attributes:
      attributeNames:
        - studentNumber
        - studentName
        - courseId
        - courseName
      name: Course Certificate
      version: '1.0'
      network: cheqd:testnet

  - id: createCredentialDefinition
    name: anoncreds/createCredentialDefinition@v1
    attributes:
      schemaId: $.actions.createSchema.output.schemaId
      tag: course
