name: Register Course Credential Template

trigger:
  type: api

input:
  type: 'object'
  properties:
    network:
      type: string
      default: 'cheqd:testnet'
      description: Mainnet is only available on the paid tiers.
      enum:
        - 'cheqd:testnet'
        - 'cheqd:mainnet'
  required:
    - network

actions:
  - id: createSchema
    name: anoncreds/createSchema@v1
    attributes:
      attributeNames:
        - studentNumber
        - studentName
        - courseId
        - courseName
      name: Course Certificate
      version: '1.0'
      network: $.input.network

  - id: createCredentialDefinition
    name: anoncreds/createCredentialDefinition@v1
    attributes:
      schemaId: $.actions.createSchema.output.schemaId
      tag: course
