name: Register Credential Template
 
# Workflow can be triggered through the API (or manually through the UI)
trigger:
  type: api
 
# Input object allows to dynamically pass the name, version and attributes of the schema
input:
  type: 'object'
  properties:
    attributeNames:
      type: array
      items:
        type: string
    name:
      type: string
    version:
      type: string
      description: Must match x.x.x or x.x (e.g. 1.0 or 1.0.0)
      default: '1.0'
    network:
      type: string
      default: 'cheqd:testnet'
      description: Mainnet is only available on the paid tiers.
      enum:
        - 'cheqd:testnet'
        - 'cheqd:mainnet'
  required:
    - name
    - version
    - attributeNames
    - network
 
actions:
  - id: createSchema
    name: anoncreds/createSchema@v1
    attributes:
      attributeNames: $.input.attributeNames
      name: $.input.name
      version: $.input.version
      network: $.input.network
 
  - id: createCredentialDefinition
    name: anoncreds/createCredentialDefinition@v1
    attributes:
      schemaId: $.actions.createSchema.output.schemaId
      tag: $.input.namename: Register Credential Template
 
# Workflow can be triggered through the API (or manually through the UI)
trigger:
  type: api
 
# Input object allows to dynamically pass the name, version and attributes of the schema
input:
  type: 'object'
  properties:
    attributeNames:
      type: array
      items:
        type: string
    name:
      type: string
    version:
      type: string
      description: Must match x.x.x or x.x (e.g. 1.0 or 1.0.0)
      default: '1.0'
    network:
      type: string
      default: 'cheqd:testnet'
      description: Mainnet is only available on the paid tiers.
      enum:
        - 'cheqd:testnet'
        - 'cheqd:mainnet'
  required:
    - name
    - version
    - attributeNames
    - network
 
actions:
  - id: createSchema
    name: anoncreds/createSchema@v1
    attributes:
      attributeNames: $.input.attributeNames
      name: $.input.name
      version: $.input.version
      network: $.input.network
 
  - id: createCredentialDefinition
    name: anoncreds/createCredentialDefinition@v1
    attributes:
      schemaId: $.actions.createSchema.output.schemaId
      tag: $.input.name