name: Verify course completion

trigger:
  type: api

input:
  type: 'object'
  properties:
    courseId:
      type: string
      description: The id of the course to enroll in
    requiredCourseId:
      type: string
      description: The id of the required course
  required:
    - courseId
    - requiredCourseId

actions:
  # Setup the connection by showing the invitationUrl as a QR code in your client
  - id: createConnection
    name: didcomm/createConnection@v1
    attributes:
      label: Silicon University

  # Request the course certificate
  - id: requestPresentation
    name: didcomm/requestPresentation@v1
    attributes:
      connectionId: $.actions.createConnection.output.connection.connectionId
      anoncreds:
        name: Course credential request
        version: '1.0.0'
        attributes:
          - names:
              - courseId
            restrictions:
              - credentialDefinitionId: did:cheqd:testnet:0d0a615e-5295-4137-8fda-0d95aca5d32b/resources/2ce68d1b-b79c-4d5e-ba7f-d321688bde8f

  # Verify that course identifier equals required course identifier
  - id: verifyCourse
    name: general/validateJson@v1
    attributes:
      data: $.actions.requestPresentation.output.presentationExchange.anoncreds.presentation.attributes[0].value
      schema:
        type: object
        properties:
          courseId:
            const: $.input.requiredCourseId
        required:
          - courseId
        additionalProperties: true
