export const PARADYM_API_KEY = process.env.PARADYM_API_KEY as string
export const ISSUE_COURSE_CERTIFICATE_WORKFLOW_ID = process.env.ISSUE_COURSE_CERTIFICATE_WORKFLOW_ID as string
export const VERIFY_COURSE_CERTIFICATE_WORKFLOW_ID = process.env.VERIFY_COURSE_CERTIFICATE_WORKFLOW_ID as string
