export const PARADYM_API_KEY = process.env.PARADYM_API_KEY as string
export const PARADYM_WEBHOOK_SECRET = process.env.PARADYM_WEBHOOK_SECRET as string
export const PARADYM_PROJECT_ID = process.env.PARADYM_PROJECT_ID as string

export const ISSUE_COURSE_CERTIFICATE_WORKFLOW_ID = process.env.ISSUE_COURSE_CERTIFICATE_WORKFLOW_ID as string
export const VERIFY_COURSE_CERTIFICATE_WORKFLOW_ID = process.env.VERIFY_COURSE_CERTIFICATE_WORKFLOW_ID as string
